dist: xenial
language: cpp

os:
    - linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - gcc-7

compiler:
    - gcc

before_install:
    - sudo apt-get install -y libmosquittopp-dev
    - sudo pip install -U cpplint

script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - gcc -v && g++ -v && cmake --version
    - cmake .
    - make

after_success:
    - cpplint *.cpp *.h
