dist: xenial
matrix:
  include:
  - language: cpp

    os:
        - linux

    services:
        - docker

    before_install:
        - sudo pip install -U cpplint

    script:
        - mkdir /tmp/out
        - docker build -t yb-image -f docker-builder/Dockerfile .
        - docker run -v /tmp/out:/mnt/out yb-image
        - docker run yb-image
        - cp /tmp/out/* .

    after_success:
        - cpplint *.cpp *.h

  - language: cpp

    os:
        - linux

    services:
        - docker

    before_install:
        - sudo pip install -U cpplint

    script:
        - docker build -t yb-image -f docker-runner/Dockerfile .
    #    - docker run yb-image

