dist: xenial
sudo: required
language: cpp

os:
    - linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6

compiler:
    - gcc
    
env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
    - sudo apt-get install -y libmosquittopp-dev
    - eval "${MATRIX_EVAL}"
    
before_script:
    - mkdir build
    - cd build
    - cmake ..
    
script:
    - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    - gcc -v && g++ -v && cmake --version
    - make && make test

